
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/QuarterShortStack/Little-Fix/issues"
[[mods]]
modId="lilfix"
version="${file.jarVersion}"
displayName="Little Fixes"
updateJSONURL="https://raw.githubusercontent.com/QuarterShortStack/Little-Fix/master/builds/versions.json"
displayURL="https://github.com/QuarterShortStack/Little-Fix"
authors="Hybolic(Brandon) and SNReloaded(Crystal)"
description='''
this mod aims to fix bugs associated with mods in the QuarterShortStack mod pack,

Current fixes:
   Cyclic Protection charms updated to 1.15 from 1.14 due to issues causing the item to not work
'''
[[dependencies.lilfix]]
    modId="cyclic"
    mandatory=true
    versionRange="[1.14.4-0.1.3]"
    ordering="AFTER"
    side="BOTH"
